#!/bin/sh

echo "> Starting iptables-server service"

# Wait a moment for network interfaces to be ready
sleep 4

# these two are already set upon container start (docker run --sysctl "net.ipv4.ip_forward=1" ...)
# sysctl -w net.ipv4.ip_forward=1
# sysctl -p

iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o eth1 -j MASQUERADE

# Keep the service running
exec tail -f /dev/null
